# Generated by Django 5.2.6 on 2025-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
