# Generated by Django 5.2.6 on 2025-12-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ocr_index_status',
            field=models.CharField(choices=[('none', 'No Index'), ('indexing', 'Indexing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='ocr_transcript_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OCRTranscript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.FloatField()),
                ('content', models.TextField()),
                ('youtube_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('vimeo_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_transcripts', to='core.course')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_transcripts', to='core.video')),
            ],
        ),
    ]
