# Generated by Django 5.2.6 on 2025-10-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_conversationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
