# Generated by Django 5.2.6 on 2025-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversation_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='vimeo_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
