# Generated by Django 5.2.6 on 2025-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_index_status_video_transcript_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
            preserve_default=False,
        ),
    ]
