# Generated by Django 5.2.6 on 2025-11-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_note_index_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
