# Generated by Django 5.2.6 on 2025-11-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_note_index_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='note',
            name='video_timestamp',
            field=models.PositiveIntegerField(),
        ),
    ]
