# Generated by Django 5.2.6 on 2025-11-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_video_duration_alter_note_video_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='index_status',
        ),
        migrations.AddField(
            model_name='video',
            name='index_status',
            field=models.CharField(choices=[('none', 'No Index'), ('indexing', 'Indexing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='none', max_length=20),
        ),
    ]
